org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.2
loader_version=0.19.3
loom_version=1.17.16

mod_version=1.0.0
maven_group=com.shiraken
archives_base_name=oleaf

fabric_api_version=0.141.5+1.21.11
modmenu_version=17.0.0
cloth_config_version=21.11.153
