org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
loom_version=1.7-SNAPSHOT

mod_version=1.0.0
maven_group=com.shiraken
archives_base_name=oleaf

fabric_api_version=0.92.2+1.20.1
modmenu_version=7.2.2
cloth_config_version=11.1.136
